/**
 * 🛰️ Provider 1 — Innertube via youtubei.js
 *
 * Talks to YouTube's internal player API with rotating client identities
 * (ANDROID / IOS / TV_EMBEDDED…). Different clients have different access
 * rules and fail at different times, so rotation is the resilience story.
 */

import type { FetchContext, ProviderOutcome, TranscriptProvider } from "../types";
import {
    absoluteTimedtextUrl,
    buildFullText,
    ok,
    parseJson3,
    parseTimedtextXml,
    pickCaptionTrack,
    type CaptionTrackRef,
} from "../shared";
import { withRetry } from "../limiter";

const CLIENT_ROTATION = ["ANDROID", "IOS", "ANDROID_VR", "TV_EMBEDDED", "MWEB", "WEB"] as const;
const YOUTUBE_HOSTED_URL = /^https?:\/\/(www\.)?youtube\.com/;

type InnerTubeInstance = {
    getBasicInfo: (
        videoId: string,
        options?: { client?: string }
    ) => Promise<InnertubeVideoInfo>;
};

interface InnertubeVideoInfo {
    captions?: { caption_tracks?: CaptionTrackRef[] } | null;
    playability_status?: { status?: string } | null;
    getTranscript?: () => Promise<InnertubeTranscriptInfo>;
}

interface InnertubeTranscriptSegment {
    start_ms?: string;
    end_ms?: string;
    snippet?: { toString(): string };
}

interface InnertubeTranscriptInfo {
    transcript?: {
        content?: {
            body?: {
                initial_segments?: InnertubeTranscriptSegment[];
            } | null;
        } | null;
    };
}

let clientPromise: Promise<InnerTubeInstance> | null = null;

async function getYoutubeClient(): Promise<InnerTubeInstance> {
    if (!clientPromise) {
        clientPromise = import("youtubei.js").then((mod) =>
            mod.Innertube.create({ retrieve_player: false }) as unknown as InnerTubeInstance
        ).catch((error) => {
            clientPromise = null;
            throw error;
        });
    }
    return clientPromise;
}

export const innertubeProvider: TranscriptProvider = {
    name: "innertube",

    async isAvailable(): Promise<boolean> {
        try {
            await getYoutubeClient();
            return true;
        } catch {
            return false;
        }
    },

    async fetch(ctx: FetchContext): Promise<ProviderOutcome> {
        let sawHealthyPlayer = false;

        try {
            const yt = await getYoutubeClient();

            for (const client of CLIENT_ROTATION) {
                let info: InnertubeVideoInfo;
                try {
                    info = (await withRetry(
                        () => yt.getBasicInfo(ctx.videoId, { client }),
                        { attempts: 2 }
                    )) as InnertubeVideoInfo;
                } catch {
                    continue;
                }

                const playability = info.playability_status?.status ?? "UNKNOWN";
                if (playability === "OK") sawHealthyPlayer = true;

                const tracks = info.captions?.caption_tracks ?? [];
                if (!tracks.length) continue;

                const track = pickCaptionTrack(tracks, ctx.preferredLang);
                if (!track?.baseUrl) continue;

                const language = track.languageCode || track.language_code || undefined;
                const isAutoGenerated = track.kind === "asr";

                // Tier A: direct timedtext fetch from the track URL.
                const segments = await fetchTimedtext(track.baseUrl);
                if (segments && segments.length > 0) {
                    return {
                        status: "ok",
                        transcript: ok({
                            segments,
                            language,
                            isAutoGenerated,
                        }),
                        detail: `client=${client}`,
                    };
                }

                // Tier B: youtubei.js high-level transcript endpoint.
                const viaApi = await fetchViaTranscriptEndpoint(info);
                if (viaApi.length > 0) {
                    return {
                        status: "ok",
                        transcript: ok({
                            segments: viaApi,
                            language,
                            isAutoGenerated,
                        }),
                        detail: `client=${client},endpoint=transcript`,
                    };
                }
            }

            if (sawHealthyPlayer) {
                return { status: "no_captions", detail: "player OK, zero caption tracks across all clients" };
            }
            return { status: "error", detail: "no client returned a playable response" };
        } catch (error) {
            return {
                status: "error",
                detail: error instanceof Error ? error.message : String(error),
            };
        }
    },
};

async function fetchTimedtext(baseUrl: string) {
    let url = absoluteTimedtextUrl(baseUrl);
    if (!YOUTUBE_HOSTED_URL.test(url)) return null;
    if (!url.includes("fmt=")) url += "&fmt=json3";

    try {
        const response = await withRetry(
            () =>
                fetch(url, {
                    headers: {
                        "User-Agent":
                            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36",
                        "Accept-Language": "en-US,en;q=0.9",
                    },
                }),
            { attempts: 2 }
        );
        if (!response.ok) return null;

        const body = await response.text();
        const trimmed = body.trim();
        if (!trimmed) return null;

        if (trimmed.startsWith("{")) {
            const parsed = parseJson3(trimmed);
            return parsed.length ? parsed : null;
        }
        const xmlParsed = parseTimedtextXml(trimmed);
        return xmlParsed.length ? xmlParsed : null;
    } catch {
        return null;
    }
}

async function fetchViaTranscriptEndpoint(info: InnertubeVideoInfo) {
    if (typeof info.getTranscript !== "function") return [];

    try {
        const transcriptInfo = (await info.getTranscript()) as InnertubeTranscriptInfo;
        const raw =
            transcriptInfo.transcript?.content?.body?.initial_segments ?? [];

        return raw
            .filter(
                (segment): segment is InnertubeTranscriptSegment & { start_ms: string } =>
                    typeof segment.start_ms === "string"
            )
            .map((segment) => {
                const startMs = parseInt(segment.start_ms, 10) || 0;
                const endMs = parseInt(segment.end_ms ?? "0", 10) || 0;
                return {
                    text: segment.snippet ? segment.snippet.toString() : "",
                    offsetMs: startMs,
                    durationMs: Math.max(0, endMs - startMs),
                };
            })
            .filter((segment) => buildFullText([segment]).length > 0);
    } catch {
        return [];
    }
}
