/**
 * ⚡ Transcript Forge — orchestrator.
 *
 * Single entry point for every transcript need in the app. Resolution order:
 *
 *   cache → caption providers (health-ordered: innertube → watchpage → ytdlp)
 *         → Whisper ASR escalation (only for verified caption-less videos)
 *
 * The orchestrator owns dedupe of concurrent identical requests, circuit-
 * breaker bookkeeping, and vault persistence. Consumers only see either a
 * TranscriptResult or a TranscriptUnavailableError.
 */

import { orderByHealth } from "./circuitBreaker";
import { getCached, setCached } from "./cache";
import {
    TranscriptUnavailableError,
    type FetchContext,
    type ProviderName,
    type ProviderOutcome,
    type TranscriptProvider,
    type TranscriptResult,
} from "./types";
import { buildFullText } from "./shared";
import { innertubeProvider } from "./providers/innertube";
import { watchPageProvider } from "./providers/watchPage";
import { ytdlpProvider } from "./providers/ytdlp";
import { whisperProvider } from "./providers/whisper";

const CAPTION_PROVIDERS: TranscriptProvider[] = [innertubeProvider, watchPageProvider, ytdlpProvider];
const ASR_PROVIDER = whisperProvider;

const VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

export interface GetTranscriptOptions {
    /** BCP-47 language preference (e.g. "en"). Defaults to English-first. */
    lang?: string;
    /** Skip both cache tiers and re-resolve from YouTube. */
    forceRefresh?: boolean;
    /**
     * Short-circuit mode for candidate judging: captions only, never ASR,
     * never persists tombstones. Cheap by design.
     */
    introOnly?: boolean;
}

const IN_FLIGHT = new Map<string, Promise<TranscriptResult>>();

function dedupeKey(videoId: string, opts: GetTranscriptOptions): string {
    return `${videoId}|${opts.lang ?? "default"}|${opts.introOnly ? "intro" : "full"}|${opts.forceRefresh ? "fresh" : "cached"}`;
}

async function resolveThroughChain(
    videoId: string,
    opts: GetTranscriptOptions
): Promise<TranscriptResult> {
    const ctx: FetchContext = { videoId, preferredLang: opts.lang };
    const attempts: string[] = [];
    let definitiveNoCaptions = false;

    const available: TranscriptProvider[] = [];
    for (const provider of orderByHealth(CAPTION_PROVIDERS)) {
        try {
            if (await provider.isAvailable()) available.push(provider);
        } catch {
            continue;
        }
    }

    for (const provider of orderByHealth(available)) {
        let outcome: ProviderOutcome;
        try {
            outcome = await provider.fetch(ctx);
        } catch (error) {
            outcome = {
                status: "error",
                detail: error instanceof Error ? error.message : String(error),
            };
        }

        if (outcome.status === "ok") {
            const result: TranscriptResult = {
                videoId,
                segments: outcome.transcript.segments,
                fullText: buildFullText(outcome.transcript.segments),
                wordCount: 0,
                language: outcome.transcript.language,
                isAutoGenerated: Boolean(outcome.transcript.isAutoGenerated),
                source: outcome.detail ? `${provider.name}(${outcome.detail})` : provider.name,
                asr: false,
            };
            result.wordCount = result.fullText.split(/\s+/).filter(Boolean).length;
            return result;
        }

        if (outcome.status === "no_captions") {
            definitiveNoCaptions = true;
            attempts.push(`${provider.name}: no_captions (${outcome.detail ?? ""})`);
        } else {
            attempts.push(`${provider.name}: error (${outcome.detail ?? "unknown"})`);
        }
    }

    if (!opts.introOnly && (await ASR_PROVIDER.isAvailable())) {
        const outcome = await ASR_PROVIDER.fetch(ctx).catch(
            (error): ProviderOutcome => ({
                status: "error",
                detail: error instanceof Error ? error.message : String(error),
            })
        );

        if (outcome.status === "ok") {
            const result: TranscriptResult = {
                videoId,
                segments: outcome.transcript.segments,
                fullText: buildFullText(outcome.transcript.segments),
                wordCount: 0,
                language: outcome.transcript.language,
                isAutoGenerated: true,
                source: "whisper-asr",
                asr: true,
            };
            result.wordCount = result.fullText.split(/\s+/).filter(Boolean).length;
            return result;
        }
        attempts.push(`whisper-asr: ${outcome.status} (${outcome.detail ?? ""})`);
    } else if (!opts.introOnly) {
        attempts.push("whisper-asr: unavailable");
    }

    throw new TranscriptUnavailableError(videoId, definitiveNoCaptions, attempts);
}

export async function getTranscript(
    videoId: string,
    opts: GetTranscriptOptions = {}
): Promise<TranscriptResult> {
    if (!VIDEO_ID_PATTERN.test(videoId)) {
        throw new TranscriptUnavailableError(videoId, false, [`invalid video id "${videoId}"`]);
    }

    if (!opts.forceRefresh) {
        const cached = await getCached(videoId, opts.lang ?? "");
        if (cached) {
            if ("tombstone" in cached) {
                throw new TranscriptUnavailableError(videoId, true, ["cached tombstone"]);
            }
            return { ...cached, source: `${cached.source} (cached)` };
        }
    }

    const key = dedupeKey(videoId, opts);
    const existing = IN_FLIGHT.get(key);
    if (existing) return existing;

    const promise = resolveThroughChain(videoId, opts)
        .then(async (result) => {
            if (!opts.introOnly) await setCached(result, videoId, opts.lang ?? "");
            return result;
        })
        .finally(() => IN_FLIGHT.delete(key));

    IN_FLIGHT.set(key, promise);
    return promise;
}

/** Introspection for debugging / ops endpoints. */
export async function providerStatus(): Promise<
    Array<{ name: ProviderName; available: boolean }>
> {
    const all = [...CAPTION_PROVIDERS, ASR_PROVIDER];
    return Promise.all(
        all.map(async (provider) => ({
            name: provider.name,
            available: await provider.isAvailable().catch(() => false),
        }))
    );
}
