/**
 * 📜 Transcript Forge — shared contracts
 *
 * Every extraction strategy implements TranscriptProvider and reports a
 * tri-state outcome so the orchestrator can distinguish "this video truly
 * has no captions" (→ escalate to ASR) from "this strategy broke"
 * (→ try next strategy).
 */

export interface TranscriptSegment {
    text: string;
    /** Offset from video start, in milliseconds. */
    offsetMs: number;
    /** Segment duration in milliseconds. */
    durationMs: number;
}

export type ProviderName = "innertube" | "watchpage" | "ytdlp" | "whisper";

export interface NormalizedTranscript {
    segments: TranscriptSegment[];
    /** BCP-47-ish language code when the upstream source exposes one. */
    language?: string;
    /** True when the track was machine-generated (ASR captions). */
    isAutoGenerated?: boolean;
}

export type ProviderOutcome =
    | { status: "ok"; transcript: NormalizedTranscript; detail?: string }
    | { status: "no_captions"; detail?: string }
    | { status: "error"; detail?: string };

export interface FetchContext {
    videoId: string;
    preferredLang?: string;
}

export interface TranscriptProvider {
    name: ProviderName;
    /** Cheap runtime capability probe (binary present, env key set…). */
    isAvailable(): Promise<boolean>;
    fetch(ctx: FetchContext): Promise<ProviderOutcome>;
}

/** Final product returned to callers, post-normalization. */
export interface TranscriptResult {
    videoId: string;
    fullText: string;
    segments: TranscriptSegment[];
    wordCount: number;
    language?: string;
    isAutoGenerated: boolean;
    /** Which strategy produced this: e.g. "innertube", "whisper-asr". */
    source: string;
    /** True when produced by speech-to-text rather than YouTube captions. */
    asr: boolean;
}

/**
 * Thrown only when every strategy is exhausted. `definitiveNoCaptions`
 * distinguishes "video verified caption-less" from "all strategies failed".
 */
export class TranscriptUnavailableError extends Error {
    readonly videoId: string;
    readonly definitiveNoCaptions: boolean;
    readonly attempts: string[];

    constructor(
        videoId: string,
        definitiveNoCaptions: boolean,
        attempts: string[]
    ) {
        super(
            definitiveNoCaptions
                ? `No transcript available for ${videoId} (verified caption-less across providers)`
                : `All transcript strategies failed for ${videoId}`
        );
        this.name = "TranscriptUnavailableError";
        this.videoId = videoId;
        this.definitiveNoCaptions = definitiveNoCaptions;
        this.attempts = attempts;
    }
}
