import { NextResponse } from "next/server";
import { getTranscript } from "@/utils/transcript";
import { TranscriptUnavailableError } from "@/utils/transcript/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(request: Request) {
    const { searchParams } = new URL(request.url);
    const videoId = searchParams.get("videoId");
    const lang = searchParams.get("lang") ?? undefined;
    const forceRefresh = ["1", "true"].includes(searchParams.get("forceRefresh") ?? "");

    if (!videoId) {
        return NextResponse.json(
            { error: "videoId is required" },
            { status: 400 }
        );
    }

    try {
        const transcript = await getTranscript(videoId, { lang, forceRefresh });

        // Legacy consumers expect {text, offset, duration} in milliseconds;
        // newer ones can use the *Ms aliases.
        const segments = transcript.segments.map((segment) => ({
            text: segment.text,
            offset: segment.offsetMs,
            duration: segment.durationMs,
            offsetMs: segment.offsetMs,
            durationMs: segment.durationMs,
        }));

        return NextResponse.json({
            videoId,
            fullText: transcript.fullText,
            segments,
            wordCount: transcript.wordCount,
            language: transcript.language ?? null,
            isAutoGenerated: transcript.isAutoGenerated,
            source: transcript.source,
            asr: transcript.asr,
        });
    } catch (error) {
        if (error instanceof TranscriptUnavailableError) {
            const verifiedCaptionless = error.definitiveNoCaptions;
            console.error(
                `Transcript unavailable for ${videoId} (verified=${verifiedCaptionless}):`,
                error.attempts.join(" | ")
            );

            return NextResponse.json(
                {
                    error: "Transcript not available",
                    message: verifiedCaptionless
                        ? "This video has no captions and automatic transcription could not produce one."
                        : "All transcript strategies failed — this may be temporary.",
                    videoId,
                    verifiedCaptionless,
                    attempts: error.attempts,
                },
                { status: 404 }
            );
        }

        console.error("Transcript fetch error:", error);
        return NextResponse.json(
            { error: "Transcript not available", message: "Unexpected failure.", videoId },
            { status: 500 }
        );
    }
}
